language: node_js

matrix:
  include:
    - node_js: 6
      script:
        - yarn cover
    - node_js: 7
      script:
        - yarn cover
    - node_js: 8
      script:
        - yarn cover
    - node_js: 9
      script:
        - yarn cover

sudo: false
