language: node_js

matrix:
  include:
    - node_js: 4
      script:
        - node --harmony node_modules/.bin/jest --config jest.json --coverage
    - node_js: 5
      script:
        - yarn cover
    - node_js: 6
      script:
        - yarn cover
    - node_js: 7
      script:
        - yarn cover

sudo: false
